name: PR Labeler

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  release-labeling:
    if: github.repository == 'callstackincubator/rock'
    name: Labeling for releasing
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: github/issue-labeler@c1b0f9f52a63158c4adc09425e858e87b32e9685 # tag v3.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/pr-labeler.yml
          enable-versioned-regex: 0
          include-title: 1
          sync-labels: 1